### PR TITLE
wazero: updates to latest with a little polish

### PR DESCRIPTION
**Pull request by codefromthecrypt**
Sorry not entirely sure about the index out of bounds thing on `make
run`, but hope this helps!

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
ps on the error:

```
Wasm File: basic.wasm
Func: view
Params: [u32(6)]
Error: wasm runtime error: runtime error: index out of range [4294967295] with length 0
wasm backtrace:
	0: vec_get
	1: unknown
```

So, there are two problems at that call site:
```
		"vec_get": func(v val.Val, i val.Val) val.Val {
			vec := h.Objects.GetVec(v) // << this is nil
			idx, err := val.ToU32(i) // << this returned 2^32-1
			if err != nil {
				panic(err)
			}
			return vec[idx] <-- so this panics because the nil vectoris being asked for element 4294967295
```

Hope this helps!

**Comment by codefromthecrypt** [comment]
ps latest wazero is a looot smaller on amd64

before:
```
8504	build/sjc
```

after:
```
6488	build/sjc
```

**Comment by codefromthecrypt** [comment]
See https://github.com/tetratelabs/wazero/pull/427 for API changes

**Comment by leighmcculloch** [comment]
Hi @codefromthecrypt! Thank for the help fixing these issues and love the development of wazero, especially the broad compatibility with the interpreter. I'm rewriting this tool to run on Deno to get at some other dependencies I want to include that exist in the NPM ecosystem, so won't need to merge this.

**Pull request closed without merging**
